apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


patchesStrategicMerge:
- deployment.yaml
- service.yaml

images:
- name: instant-search-demo
  newName: localhost:5000/instant-search-demo
  newTag: v0.1
resources:
- ../../base
